In [2]:
import numpy as np

#num_labels
K = 3

# num_samples 
N = 9

labels = [0, 0, 0, 1, 1, 1, 2, 2, 2]
labels = np.array(labels)
print(labels)

[0 0 0 1 1 1 2 2 2]


In [3]:
# create an NxK array
labels_onehot = np.zeros((N, K))

# one-hot encoding
labels_onehot[np.arange(N), labels] = 1
print(labels_onehot)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
