In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print(arr)
arr = np.zeros(4)
print(arr)
arr = np.arange(1, 4, 2)
print(arr)
arr = np.random.rand(2)
print(arr)
arr = np.empty(3)
print(arr)

[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.18470064 0.87510646]
[4.9e-324 9.9e-324 1.5e-323]


In [3]:
arr = np.array(
    [[1, 2, 3], [1, 2, 3]],
    dtype=float
)
print(arr)

arr = np.zeros((2, 4))
print(arr)

arr = np.full((1, 4), 2.0)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 2. 2. 2.]]


In [4]:
arr = np.array(
    [[1, 2, 3], [1, 2, 3]], dtype=float
)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)
print(arr.data)
arr

2
6
float64
(2, 3)
8


array([[1., 2., 3.],
       [1., 2., 3.]])

In [5]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(arr[0])

arr[1] = 3.0
print(arr)

print(arr[-4])

arr[-3] = 2.0
print(arr)

1.0
[1. 3. 3. 4.]
1.0
[1. 2. 3. 4.]


In [6]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]])

print(arr[0][3])
print(arr[-2][3])

arr[1] = 3.0
print(arr)

arr[0][-3] = 3.0
print(arr)

4.0
4.0
[[1. 2. 3. 4.]
 [3. 3. 3. 3.]]
[[1. 3. 3. 4.]
 [3. 3. 3. 3.]]


In [7]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(arr[0])
print(arr[0][0::2])

print(arr[0:2,1:3])
print(arr[0:2,-4::2])

[1. 2. 3. 4.]
[1. 3.]
[[2. 3.]
 [6. 7.]]
[[1. 3.]
 [5. 7.]]


In [8]:
arr = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])
print(arr.shape)

arr = np.reshape(arr, (3, 2))
print(arr)
print(arr.shape)

arr = np.reshape(arr, (3, 3)) # Error

(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


ValueError: cannot reshape array of size 6 into shape (3,3)

In [9]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 6.0, 7.0, 8.0])

print(arr1 + arr2)
print(np.add(arr1, arr2))

print(arr1 % arr2)
print(np.mod(arr1, arr2))

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [10]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([5.0, 2.0, 7.0, 8.0])

print(arr1 < arr2)
print(np.less(arr1, arr2))

print(arr1 != arr2)
print(np.not_equal(arr1, arr2))

np.logical_or(
    np.less(arr1, arr2),
    np.not_equal(arr1, arr2)
)

[ True False  True  True]
[ True False  True  True]
[ True False  True  True]
[ True False  True  True]


array([ True, False,  True,  True])

In [11]:
arr = np.random.rand(2, 3)
print(arr)

print(np.sin(arr))

print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))

[[0.14840133 0.52822312 0.0042772 ]
 [0.19624005 0.79206581 0.73226381]]
[[0.14785722 0.50399944 0.00427719]
 [0.19498293 0.71180576 0.66855486]]
[[0. 1. 0.]
 [0. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr = np.array([1.0, 2.0, 3.0, 4.0])
print(np.max(arr))

arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])
print(np.max(arr))
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))

4.0
8.0
[5. 6. 7. 8.]
[4. 8.]


In [13]:
arr1 = np.array(['Iphone: ', 'Price: '])
arr2 = np.array(['15', '$900'])

print(np.char.add(arr1, arr2))
print(np.char.multiply(arr1, 3))
print(np.char.upper(arr1))
print(np.char.equal(arr1, arr2))

['Iphone: 15' 'Price: $900']
['Iphone: Iphone: Iphone: ' 'Price: Price: Price: ']
['IPHONE: ' 'PRICE: ']
[False False]


In [14]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([[1.0], [5.0]])

print(arr1)
print(arr2)

print(np.add(arr1, 3.0))

print(np.add(arr1, arr2))

[1. 2. 3. 4.]
[[1.]
 [5.]]
[4. 5. 6. 7.]
[[2. 3. 4. 5.]
 [6. 7. 8. 9.]]


In [16]:
arr = np.array([1., 2., 3.])
print(np.dot(arr, 2))

[2. 4. 6.]


In [17]:
arr_1 = np.array([1., 2., 3.])
arr_2 = np.array([1., 2., 1.])
print(np.dot(arr_1, arr_2))

8.0


In [21]:
arr_1 = np.array([
    [3., 4., 1.], [4., 3., 2.]
])
arr_2 = np.array([
    [1., 2.], [0., 1.], [2., 0.]
])
print(np.dot(arr_1, arr_2))

[[ 5. 10.]
 [ 8. 11.]]


In [22]:
arr = np.array([
    [1, 2, 3], [3, 4, 5]
])

print(np.transpose(arr))
print(np.transpose(arr).shape)

print(arr.flatten())
print(arr.flatten().shape)

[[1 3]
 [2 4]
 [3 5]]
(3, 2)
[1 2 3 3 4 5]
(6,)
