### Sigmoid

In [1]:
import torch
import torch.nn as nn

sigmoid_function = nn.Sigmoid()
data = torch.Tensor([1, 2, 3])
output = sigmoid_function(data)
print(output)

tensor([0.7311, 0.8808, 0.9526])


In [6]:
class MySigmoid(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 1 / (1 + torch.exp(-x))

In [7]:
my_sigmoid = MySigmoid()
output = my_sigmoid(data)
print(output)

tensor([0.7311, 0.8808, 0.9526])


## Relu

In [7]:
import torch
import torch.nn as nn

class MyReluActivation(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return torch.clamp(x, min=0)

In [8]:
data = torch.Tensor([1, -2, 3])
my_relu = MyReluActivation()
output = my_relu(data)
print(output)

tensor([1., 0., 3.])
