In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
# print current working directory
!pwd

/content/drive/MyDrive/Colab_Notebooks/AIO/Teaching_Assistant/01_Numpy/02_Codes


# How to create Arrays?

In [ ]:
# Create a list
lst = ["AIO", 2025, 3.14, -1, True, [1, 2, 3],]
print("List:",lst)

In [ ]:
# Create a list using list comprehension
n = 5
lst_zeros = [0]*n
print("Initialised list with zeros:",lst_zeros)

In [ ]:
import numpy as np

arr = np.array([2, 0, 2, 5, 7, 1])
print("Create an array:", arr)

Create an array: [2 0 2 5 7 1]


In [ ]:
import numpy as np

# Convert list into array of integers
lst_int = [2, 0, 2, 5, 7, 1]
arr_int = np.array(lst_int)
print("Array from list:", arr_int)

Array from list: [2 0 2 5 7 1]


In [ ]:
# import numpy as np

# # Create an array of n floats and initialise it with zeros
# n = 5
# arr_zeros = np.zeros(n)
# print("Initialised array with zeros:", arr_zeros)

Initialised array with zeros: [0. 0. 0. 0. 0.]


In [ ]:
# import numpy as np

# # Convert list into array of integers
# lst = ["AIO", 2025, 3.14, -1, True, [1, 2, 3],]
# arr = np.array(lst)
# print("Array from list:", arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

# Array indexing and slicing

In [ ]:
# Create a list
l_data = [4, 5, 6, 7, 8, 9]
l_data[2], l_data[-4]

(6, 6)

In [ ]:
# Create a list
l_data = [4, 5, 6, 7, 8, 9]

print(l_data[:3])
print(l_data[3:])
print(l_data[2:4])

print(l_data[::2])
print(l_data[-5::2])

[4, 5, 6]
[7, 8, 9]
[6, 7]
[4, 6, 8]
[5, 7, 9]


In [ ]:
import numpy as np

a_data = np.array([4, 5, 6, 7, 8, 9])

print(a_data[2])
print(a_data[-4])

print(a_data[:3])
print(a_data[3:])
print(a_data[2:4])

print(a_data[-6::2])
print(a_data[1::2])

6
6
[4 5 6]
[7 8 9]
[6 7]
[4 6 8]
[5 7 9]


# Add an element

In [ ]:
import numpy as np

# Create a list
l_data = [4, 5, 6, 7, 8, 9]

# Create an array
a_data = np.array([4, 5, 6, 7, 8, 9])


# List
l_data.append(0)
print(l_data)

# Array
a_data = np.append(a_data, 0)
print(a_data)


[4, 5, 6, 7, 8, 9, 0]
[4 5 6 7 8 9 0]


In [ ]:
import numpy as np

# Create a list
l_data = [4, 5, 6, 7, 8, 9]

# Create an array
a_data = np.array([4, 5, 6, 7, 8, 9])

# List
l_data.insert(0, 1)
print(l_data)

# Array
a_data = np.insert(a_data, 0, 1)
print(a_data)

[1, 4, 5, 6, 7, 8, 9]
[1 4 5 6 7 8 9]


# Update an element

In [ ]:
import numpy as np

# Create a list
l_data = [4, 5, 6, 7, 8, 9]

# Create an array
a_data = np.array([4, 5, 6, 7, 8, 9])

# List
l_data[2] = 1
print(l_data)

# array
a_data[2] = 1
print(a_data)

[4, 5, 1, 7, 8, 9]
[4 5 1 7 8 9]


In [ ]:
import numpy as np

# Create a list
l_data = [4, 5, 6, 7, 8, 9]

# Create an array
a_data = np.array([4, 5, 6, 7, 8, 9])

# List
l_data.extend([2, 3])
print(l_data) # in-place

# array
np.append(a_data, [2, 3],) # Will a_data is updated like list? No
print(a_data) # What is the output? [the old data array]
# Why? [bc numpy arrange a fixed array, cant be modified, only allocate new memory]

[4, 5, 6, 7, 8, 9, 2, 3]
[4 5 6 7 8 9]


In [ ]:
# array
new_arr = np.append(a_data, [2, 3],)
print(new_arr) # What is the output? Why?

[4 5 6 7 8 9 2 3]


# + and * operators

In [ ]:
import numpy as np

# Create a list
lst_1 = [6, 8]
lst_2 = [7, 9]

# Create an array
arr_1 = np.array([6, 8])
arr_2 = np.array([7, 9])


# list
print(lst_1 + lst_2)

# array
print(np.append(arr_1, arr_2))

# list
print(lst_1 * 3)

# array
print(arr_1 * 3)


[6, 8, 7, 9]
[6 8 7 9]
[6, 8, 6, 8, 6, 8]
[18 24]


In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 6, 8, 3, 9]

# Create an array
arr = np.array([2, 1, 6, 8, 3, 9])


# list
lst.sort()
print(lst)

# array
arr.sort()
print(arr)

[1, 2, 3, 6, 8, 9]
[1 2 3 6 8 9]


In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 6, 8, 3, 9]

# Create an array
arr = np.array([2, 1, 6, 8, 3, 9])


# list
lst.sort(reverse=True)
print(lst)

# array
arr.sort()
arr = arr[::-1]
print(arr)

[9, 8, 6, 3, 2, 1]
[9 8 6 3 2 1]


# Delete an element

In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

# list
lst.pop(2)
print(lst)

# array
arr = np.delete(arr, 2)
print(arr)

[2, 1, 8, 5, 9]
[2 1 8 5 9]


In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

# list
lst.remove(5)
# lst.remove(5)
print(lst)

# array
del_indice = np.where(arr == 5)[0]
arr = np.delete(arr, del_indice)
print(arr)

[2, 1, 8, 5, 9]
[2 1 8 9]


In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

# list
del lst[1:3]
print(lst)

# array
arr_1 = np.delete(arr, np.arange(1,3))
print(arr_1)

arr_2 = np.concatenate((arr[:1], arr[3:]))
print(arr_2)

[2, 8, 5, 9]
[2 8 5 9]
[2 8 5 9]


# Index

In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

#list
print(lst.index(5))

# array
print(np.where(arr==5)[0][0])

2
2


In [ ]:
l_x = [0, 0.25, 0.5, 0.75, 1.0]

# Indexing list
l_y = l_x[1:4] #  [0.25, 0.5, 0.75]

#
l_y[-1] = 1000.0
print("Re-Check elements of list y: \n", l_y)
print("Re-Check elements of list x: \n", l_x)

Re-Check elements of list y: 
 [0.25, 0.5, 1000.0]
Re-Check elements of list x: 
 [0, 0.25, 0.5, 0.75, 1.0]


In [ ]:
import numpy as np
x = np.linspace(0.0, 1.0, 5)
print("Array x: \n", x)

# array assignment
y = x[1:4]
# print("Check elements of array y: \n", y)
y[-1] = 1000.0

# Check elements of array x
print("Re-Check elements of array y: \n", y)
print("Re-Check elements of array x: \n", x)


Array x: 
 [0.   0.25 0.5  0.75 1.  ]
Re-Check elements of array y: 
 [2.5e-01 5.0e-01 1.0e+03]
Re-Check elements of array x: 
 [0.0e+00 2.5e-01 5.0e-01 1.0e+03 1.0e+00]


# count() and copy()

In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

#list
print(lst.count(5))

# array
print(np.sum(arr==5))

2
2


# len(), min(), max(), sum()

In [ ]:
import numpy as np

# Create a list
lst = [6, 5, 7, 1, 9, 2]

# Create an array
arr = np.array([6, 5, 7, 1, 9, 2])

#list
print('For list:')
print(len(lst))
print(min(lst))
print(max(lst))
print(sum(lst))

# array
print('For array:')
print(len(arr))
print(np.min(arr))
print(np.max(arr))
print(arr.shape)
print(np.sum(arr))

For list:
6
1
9
30
For array:
6
1
9
(6,)
30


# zip()

In [ ]:
predictions = [1, 0, 1, 1, 0]
ground_truth = [1, 1, 1, 0, 0]

# Use zip to pair predictions with labels
for pred, true in zip(predictions, ground_truth):
    result = "Correct" if pred == true else "Incorrect"
    print(f"Predicted: {pred}, Actual: {true} → {result}")

Predicted: 1, Actual: 1 → Correct
Predicted: 0, Actual: 1 → Incorrect
Predicted: 1, Actual: 1 → Correct
Predicted: 1, Actual: 0 → Incorrect
Predicted: 0, Actual: 0 → Correct


In [ ]:
import numpy as np

# Create a list
lst = [6, 1, 7]

# create an array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Zip-like operation using np.dstack()
zipped_arr = np.dstack((arr1, arr2))[0]
print(zipped_arr)

for i in range(len(arr1)):
    print(zipped_arr[i])


[[1 4]
 [2 5]
 [3 6]]
[1 4]
[2 5]
[3 6]


# List - enumerate()

In [ ]:
import numpy as np

# create a list
data = [6, 1, 7]

# get index and value
print('Method 1:')
length = len(data)
for index in range(length):
    print(index, data[index])

# enumerate
print('Method 2:')
for index, value in enumerate(data):
    print(index, value)

Method 1:
0 6
1 1
2 7
Method 2:
0 6
1 1
2 7


# Array - np.ndenumerate()

In [ ]:
import numpy as np

# create a list
data = [6, 1, 7]

for idx, val in np.ndenumerate(data):
    print(idx, val)

(0,) 6
(1,) 1
(2,) 7


# List examples

In [ ]:
lst = [6, 5, 7, 1, 9, 2]

# Sum of even numbers

def sum1(data):
    result = 0

    for val in data:
        if val % 2 == 0:
            result = result + val

    return result

summation = sum1(lst)
print(summation)

# Sum of numbers with even indices

def sum2(data):
    result = 0

    length = len(data)

    for idx in range(length):
        if idx % 2 == 0:
            result = result + data[idx]

    return result

summation = sum2(lst)
print(summation)

8
22


In [ ]:
lst = [6, 5, 7, 1, 9, 2]
def sum3(data):
    result = 0

    # length = len(data)

    for idx, val in enumerate(data):
        if idx % 2 == 0:
            result = result + val

    return result

summation = sum3(lst)
print(summation)

22


# Array examples

In [ ]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Sum of even numbers
## Using boolean indexing to find even numbers
even_num = arr[arr % 2 == 0]

## Calculate sum
sum_even_num = np.sum(even_num)

print('Original array:', arr)
print('Even number:', even_num)
print('Sum of even numbers:', sum_even_num)

# Sum of even numbers
## Select elements at even indices
even_idx_element = arr[::2]

## Calculate sum
sum_even_indices = np.sum(even_idx_element)

print('Original array:', arr)
print('Even number:', even_idx_element)
print('Sum of even numbers:', sum_even_indices)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Even number: [ 2  4  6  8 10]
Sum of even numbers: 30
Original array: [ 1  2  3  4  5  6  7  8  9 10]
Even number: [1 3 5 7 9]
Sum of even numbers: 25


# 2D list and 2D array

In [ ]:
import numpy as np

# Create 2D list
list_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print('2D list:', list_2d)

# Accessing element at (1,2)
print('Element at (1,2) of 2D list:', list_2d[1][2])

# Create 2D array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print('2D array:\n', array_2d)

# Accessing element at (1,2)
print('Element at (1,2) of 2D array:', array_2d[1, 2])

2D list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at (1,2) of 2D list: 6
2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2) of 2D array: 6


# Array manipulation

In [ ]:
# Reshaping
# Change the shape of an array without changing its data
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [ ]:
# Flattening
# Convert a multi-dimensional array into 1D array
arr = np.array([[1, 2], [3, 4]])
print("Array before flattening:\n",arr)
print("Flattened array:", arr.flatten())

Array before flattening:
 [[1 2]
 [3 4]]
Flattened array: [1 2 3 4]


In [ ]:
# Concatenation
# Joining two or more arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Concatenated array:", np.concatenate((arr1, arr2)))

Concatenated array: [1 2 3 4 5 6]



# Broadcasting and Vectorization

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2])

print('Array a:\n', a)
print('Array b:\n', b)
result = a + b
print('Array a + Array b: \n', result)

Array a:
 [[1 2]
 [3 4]
 [5 6]]
Array b:
 [1 2]
Array a + Array b: 
 [[2 4]
 [4 6]
 [6 8]]


Evaluates f(x)=\sin(x)e^{(-x)} at 10e6 equispaced points within [0, 2π]

In [ ]:
# Non-vectorized VS vectorized code (performance)
import math
import numpy as np
n = 1_000_000
x = np.linspace(0.0, 2.0*math.pi, n)
y = np.zeros(n)

%timeit for i in range(0,len(x)): \
y[i] = math.sin(x[i])*math.exp(-x[i])

266 ms ± 8.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# Non-vectorized VS vectorized code (performance)
import math
import numpy as np
n = 1_000_000
x = np.linspace(0.0, 2.0*math.pi, n)
y = np.zeros(n)

%timeit y = np.sin(x)*np.exp(-x)

21.4 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
import numpy as np
import time

# Vectorized version of f(x)
def f(x):
    return x**3 + np.sin(x) * np.exp(-3*x)

# Scalar (loop-based) version of f(x)
def f_scalar(x_array):
    results = []
    for x in x_array:
        results.append(x**3 + np.sin(x) * np.exp(-3*x))
    return np.array(results)

# Array sizes to test
sizes = [10, 100, 1000, 10_000, 100_000]

# Measure and compare performance
for size in sizes:
    x = np.linspace(0, 1, size)

    # Vectorized timing
    start = time.perf_counter()
    y_vec = f(x)
    end = time.perf_counter()
    t_vec = (end - start) * 1000  # convert to ms

    # Scalar timing
    start = time.perf_counter()
    y_sca = f_scalar(x)
    end = time.perf_counter()
    t_sca = (end - start) * 1000  # convert to ms

    speedup = t_sca / t_vec if t_vec > 0 else float('inf')

    print(f"{size:<10}{t_vec:<20.4f}{t_sca:<20.4f}{speedup:.1f}x")

Size      Vectorized (ms)     Scalar (ms)         Speedup (x)
------------------------------------------------------------
10        0.0383              0.0371              1.0x
100       0.0335              0.1866              5.6x
1000      0.5082              2.9573              5.8x
10000     1.3810              17.2290             12.5x
100000    4.2362              173.8604            41.0x


List multiplication time: 4.1971 ms
NumPy array multiplication time: 0.1146 ms


# Practice Numpy Array

In [ ]:
import numpy as np

# Create the first array
arr_1 = np.arange(10).reshape((2,-1))
print("The first array:\n",arr_1)

# Create the second array
arr_2 = np.repeat(8,10).reshape((2,-1))
print("The second array:\n",arr_2)

The first array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
The second array:
 [[8 8 8 8 8]
 [8 8 8 8 8]]


In [ ]:
# Method 1
new_arr = np.concatenate((arr_1, arr_2), axis=0)
print("Concatenated array:\n",new_arr)

# Method 2
new_arr = np.vstack((arr_1,arr_2))
print("Veritally stack arrays:\n",new_arr)

# Method 3
new_arr = np.r_[arr_1,arr_2]
print("Veritally stack arrays:\n",new_arr)

Concatenated array:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [8 8 8 8 8]
 [8 8 8 8 8]]
Veritally stack arrays:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [8 8 8 8 8]
 [8 8 8 8 8]]
Veritally stack arrays:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [ ]:
# Method 1
new_arr = np.concatenate((arr_1, arr_2), axis=1)
print("Concatenated array:\n",new_arr)

# Method 2
new_arr = np.hstack((arr_1,arr_2))
print("Horizontally stack arrays:\n",new_arr)

# Method 3
new_arr = np.c_[arr_1,arr_2]
print("Horizontally stack arrays:\n",new_arr)

Concatenated array:
 [[0 1 2 3 4 8 8 8 8 8]
 [5 6 7 8 9 8 8 8 8 8]]
Horizontally stack arrays:
 [[0 1 2 3 4 8 8 8 8 8]
 [5 6 7 8 9 8 8 8 8 8]]
Horizontally stack arrays:
 [[0 1 2 3 4 8 8 8 8 8]
 [5 6 7 8 9 8 8 8 8 8]]


Veritally stack arrays:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [ ]:
import numpy as np

# create an array
arr = np.array([1, 8, 2, 5, 4, 6, 0, 7, 9, 3])

# Method 1
idx = np.where(arr < 7)
out = arr[idx]
print(out)

# Method 2
out = arr[arr<7]
print(out)

[1 2 5 4 6 0 3]
[1 2 5 4 6 0 3]


In [ ]:
import numpy as np

# Create the first array
arr_1 = np.arange(10).reshape((2,-1))
print("The first array:\n",arr_1)

# Create the second array
arr_2 = np.array([2,5,1,9,7,3,8,6,0,4]).reshape((2,-1))
print("The second array:\n",arr_2)

# Create a user-defined function
def get_max(x, y):
    if x >= y:
        return x
    else:
        return y

The first array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
The second array:
 [[2 5 1 9 7]
 [3 8 6 0 4]]


In [ ]:
# Vectorize the function
element_wise_compare = np.vectorize(get_max, otypes=[int])

# Method 1: Apply the function
out1 = element_wise_compare(arr_1, arr_2)
print("Output using the first method:\n",out1)

# Method 2: Using np.maximum
out2 = np.maximum(arr_1, arr_2)
print("Output using the second method:\n",out2)

# Method 3: Using np.where()
out3 = np.where(arr_1 > arr_2, arr_1, arr_2)
print("Output using the third method:\n",out3)

Output using the first method:
 [[2 5 2 9 7]
 [5 8 7 8 9]]
Output using the second method:
 [[2 5 2 9 7]
 [5 8 7 8 9]]
Output using the third method:
 [[2 5 2 9 7]
 [5 8 7 8 9]]


In [ ]:
import numpy as np

u = np.array([1, 2, 4, 2])

# Compute the length of vector u
print("Length of vector u:", np.linalg.norm(u))


Length of vector u: 5.0


In [ ]:
import numpy as np

# Create two vectors
u = np.array([1, 2, 3, 4])
v = np.array([5, 6, 7, 8])

# Add two vectors
out_1 = u + v
out_2 = np.add(u, v)

print("Out 1:\n",out_1)
print("Out 2:\n",out_2)

Out 1:
 [ 6  8 10 12]
Out 2:
 [ 6  8 10 12]


In [ ]:
import numpy as np

# Create two vectors
u = np.array([1, 2, 3, 4])
v = np.array([5, 6, 7, 8])

# Dot Product
out_1 = u * v
out_2 = v * u
out_3 = np.multiply(u, v)

print("Out 1:\n",out_1)
print("Out 2:\n",out_2)
print("Out 3:\n",out_3)

Out 1:
 [ 5 12 21 32]
Out 2:
 [ 5 12 21 32]
Out 3:
 [ 5 12 21 32]


In [ ]:
import numpy as np

# Create two vectors
u = np.array([1, 2, 3, 4])
v = np.array([5, 6, 7, 8])

# Dot Product
out_1 = u.dot(v)
out_2 = np.dot(v, u)
out_3 = np.dot(u, v)

print("Out 1:\n",out_1)
print("Out 2:\n",out_2)
print("Out 3:\n",out_3)

Out 1:
 70
Out 2:
 70
Out 3:
 70


In [ ]:
import time
import numpy as np

def multiply_lists(size=1000):
    list1 = list(range(size))
    list2 = list(range(size))

    start = time.perf_counter()
    result = [(a * b) for a, b in zip(list1, list2)]
    end = time.perf_counter()

    elapsed_ms = (end - start) * 1000
    print(f"List multiplication time: {elapsed_ms:.4f} ms")

def multiply_arrays(size=1000):
    arr1 = np.arange(size)
    arr2 = np.arange(size)

    start = time.perf_counter()
    result = arr1 * arr2
    end = time.perf_counter()

    elapsed_ms = (end - start) * 1000
    print(f"NumPy array multiplication time: {elapsed_ms:.4f} ms")

# Run both
size = 100000
multiply_lists(size)
multiply_arrays(size)

List multiplication time: 20.2035 ms
NumPy array multiplication time: 0.1983 ms


In [ ]:
import numpy as np
x = np.linspace(0.0, 1.0, 5)
print("Array x: \n", x)

# array assignment
y = x
y[-1] = 1000.0

# Check elements of array x
print("Check elements of array y: \n", y)
print("Check elements of array x: \n", x)

Array x: 
 [0.   0.25 0.5  0.75 1.  ]
Check elements of array y: 
 [0.0e+00 2.5e-01 5.0e-01 7.5e-01 1.0e+03]
Check elements of array x: 
 [0.0e+00 2.5e-01 5.0e-01 7.5e-01 1.0e+03]


Re-Check elements of list y: 
 [0.25, 0.5, 1000.0]
Re-Check elements of list x: 
 [0, 0.25, 0.5, 0.75, 1.0]


In [ ]:
def array_addition_w1(a, b):
    a = a + b

def array_addition_w2(a, b):
    a += b

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])

# Use the first addition function
array_addition_w1(a, b)
print("Array a:", a)

Array a: [1. 2. 3.]


In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 5.0, 6.0])

# Use the second addition function
array_addition_w2(a, b)
print("Array a:", a)


Array a: [5. 7. 9.]


In [ ]:
import numpy as np

data = np.arange(1, 3, 0.5)
print(data)


[1.  1.5 2.  2.5]


In [ ]:
data = np.array([1,2])
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2])

In [ ]:
data = np.arange(6).reshape(2,3)
data[:,1]

array([1, 4])

In [ ]:
data = np.arange(3,7)
out = data[[0,1,3,2]]

print(out)

[3 4 6 5]


In [ ]:
data = np.arange(16).reshape(4,4)
data[:3,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
import numpy as np

In [ ]:
def sum_of_element(arr):
  return np.sum(arr)

In [ ]:
arr2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])

In [ ]:
result = np.apply_along_axis(sum_of_element, 0, arr2d)
print(result)

[12 15 18]
