In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# New Section

In [ ]:
# Create a list
lst = ["AIO", 2025, 3.14, -1, True, [1, 2, 3],]

print("List:",lst)

List: ['AIO', 2025, 3.14, -1, True, [1, 2, 3]]


In [ ]:
n = 5
lst_zeros = [0]*n
print(lst_zeros)

[0, 0, 0, 0, 0]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
n = 5
arr_zeros = np.zeros(n)
print(arr_zeros)

[0. 0. 0. 0. 0.]


In [ ]:
lst = ["AIO", 2025, 3.14, -1, True, [1, 2, 3]]
arr_from_lst = np.array(lst)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

In [ ]:
import numpy as np

# Create a list
l_data = [4, 5, 6, 7, 8, 9]

# Create an array
a_data = np.array([4, 5, 6, 7, 8, 9])

# List
l_data.extend([2, 3])
print(l_data) # in-place

[4, 5, 6, 7, 8, 9, 2, 3]


In [ ]:
# array
# Create an array
a_data = np.array([4, 5, 6, 7, 8, 9])

print('Array:', a_data)

arr_2 = np.append(a_data, [2, 3])

print(arr_2)
print(a_data)

Array: [4 5 6 7 8 9]
[4 5 6 7 8 9 2 3]
[4 5 6 7 8 9]


In [ ]:
a_data = np.array([4, 5, 6, 7, 8, 9])
a_data[::-1]

array([9, 8, 7, 6, 5, 4])

In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

# list
lst.remove(5)
print(lst)

[2, 1, 8, 5, 9]


In [ ]:
del_indice = np.where(arr == 5)
del_indice
arr = np.delete(arr, del_indice[0])
print(arr)

[2 1 8 9]


In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

In [ ]:
print(lst.index(5))

2


In [ ]:
print(np.where(arr==5)[0][0])

2


In [ ]:
l_x = [0, 0.25, 0.5, 0.75, 1.0]

# Indexing list
l_y = l_x[1:4] #  [0.25, 0.5, 0.75]
print(l_y)
#
l_y[-1] = 1000.0
print("Re-Check elements of list y: \n", l_y)
print("Re-Check elements of list x: \n", l_x)

[0.25, 0.5, 0.75]
Re-Check elements of list y: 
 [0.25, 0.5, 1000.0]
Re-Check elements of list x: 
 [0, 0.25, 0.5, 0.75, 1.0]


In [ ]:
import numpy as np
x = np.linspace(0.0, 1.0, 5)
print("Array x: \n", x)

# array assignment
y = x[1:4]
# print("Check elements of array y: \n", y)
y[-1] = 1000.0

# Check elements of array x
print("Re-Check elements of array y: \n", y)
print("Re-Check elements of array x: \n", x)

Array x: 
 [0.   0.25 0.5  0.75 1.  ]
Re-Check elements of array y: 
 [2.5e-01 5.0e-01 1.0e+03]
Re-Check elements of array x: 
 [0.0e+00 2.5e-01 5.0e-01 1.0e+03 1.0e+00]


In [ ]:
import numpy as np

# Create a list
lst = [2, 1, 5, 8, 5, 9]

# Create an array
arr = np.array([2, 1, 5, 8, 5, 9])

np.sum(arr == 5)

np.int64(2)

In [ ]:
predictions = [1, 0, 1, 1, 0]
ground_truth = [1, 1, 1, 0, 0]

# Use zip to pair predictions with labels
for pred, true in zip(predictions, ground_truth):
    result = "Correct" if pred == True else "Incorrect"
    print(f"Predicted: {pred}, Actual: {true} → {result}")

Predicted: 1, Actual: 1 → Correct
Predicted: 0, Actual: 1 → Incorrect
Predicted: 1, Actual: 1 → Correct
Predicted: 1, Actual: 0 → Correct
Predicted: 0, Actual: 0 → Incorrect


In [ ]:
# create an array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Zip-like
zip_arr = np.dstack((arr1, arr2))[0]
zip_arr

for i in range(len(arr1)):
    print(zip_arr[i])

[1 4]
[2 5]
[3 6]


In [ ]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

## Select elements at even indices
even_idx_element = arr[::2]
print(even_idx_element)
print('Result:', np.sum(even_idx_element))

[1 3 5 7 9]
Result: 25


In [ ]:
# Create 2D array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(array_2d.shape)

(3, 3)


In [ ]:
array_2d[1,1]

np.int64(5)

In [ ]:
# Change the shape of an array without changing its data
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)

# reshape (2, 3)
print(arr.reshape(2,3))

print("Flattened array:", arr.flatten())


(3, 2)
[[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
print("array a:", a)
b = np.array([1, 2])
print("array b:", b)

print("Sum of a and b:",a + b)

array a: [[1 2]
 [3 4]
 [5 6]]
array b: [1 2]
Sum of a and b: [[2 4]
 [4 6]
 [6 8]]


In [ ]:
# Non-vectorized VS vectorized code (performance)
import math
import numpy as np
n = 1_000_000
x = np.linspace(0.0, 2.0*math.pi, n)
y = np.zeros(n)

%timeit for i in range(0,len(x)): \
y[i] = math.sin(x[i])*math.exp(-x[i])

700 ms ± 191 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
import math
import numpy as np
n = 1_000_000
x = np.linspace(0.0, 2.0*math.pi, n)
y = np.zeros(n)

%timeit y = np.sin(x)*np.exp(-x)

50.5 ms ± 2.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
import numpy as np
import time

# Vectorized version of f(x)
def f(x):
    return x**3 + np.sin(x) * np.exp(-3*x)

# Scalar (loop-based) version of f(x)
def f_scalar(x_array):
    results = []
    for x in x_array:
        results.append(x**3 + np.sin(x) * np.exp(-3*x))
    return np.array(results)

# Array sizes to test
sizes = [10, 100, 1000, 10_000, 100_000]

# Measure and compare performance
for size in sizes:
    x = np.linspace(0, 1, size)

    # Vectorized timing
    start = time.perf_counter()
    y_vec = f(x)
    end = time.perf_counter()
    t_vec = (end - start) * 1000  # convert to ms

    # Scalar timing
    start = time.perf_counter()
    y_sca = f_scalar(x)
    end = time.perf_counter()
    t_sca = (end - start) * 1000  # convert to ms

    speedup = t_sca / t_vec if t_vec > 0 else float('inf')

    print(f"{size:<10}{t_vec:<20.4f}{t_sca:<20.4f}{speedup:.1f}x")

10        0.0709              0.0705              1.0x
100       0.0480              0.4376              9.1x
1000      0.0967              4.3019              44.5x
10000     2.1648              41.3877             19.1x
100000    10.5412             962.3938            91.3x


In [ ]:
arr = np.array([1, 8, 2, 5, 4, 6, 0, 7, 9, 3])

idx = np.where(arr < 7)
print(idx)

out = arr[idx]
print(out)

(array([0, 2, 3, 4, 5, 6, 9]),)
[1 2 5 4 6 0 3]


In [ ]:
arr_1 = np.arange(10).reshape((2,-1))
arr_2 = np.array([2,5,1,9,7,3,8,6,0,4]).reshape((2,-1))

# np.where
out = np.where(arr_1 > arr_2, arr_1, arr_2)
print(out)

[[2 5 2 9 7]
 [5 8 7 8 9]]


In [ ]:
import numpy as np
data = np.arange(1, 3, 0.5)
print(data)

[1.  1.5 2.  2.5]


In [ ]:
import numpy as np
# given
data = np.array([70, 250])
data = data.astype(np.uint8)
print(data)

# ....
# first
data = data.astype(float)

data = data + 50
print(data)

# clip
data = np.clip(data, 0, 255)
data = data.astype(np.uint8)
print(data)

In [ ]:
import numpy as np
data = np.array([70, 250])
data = data.astype(np.uint8)
print(data)

[ 70 250]


In [ ]:
data = data.astype(float)

data = data + 50
print(data)

[120. 300.]


In [ ]:
data = np.clip(data, 0, 255)
data

array([120., 255.])

In [ ]:
import numpy as np
x = np.array([1, 2, 3])
m = x.max()
x_i = x - m
exp_x = np.exp(x_i)
total = np.sum(exp_x)
result = exp_x/total
print(result)

[0.09003057 0.24472847 0.66524096]


In [ ]:
import numpy as np

matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7, 1],
           [6, 5, 4, 2],
           [3, 2, 1, 4]]

matrix2_nrows = len(matrix2[0])
print(matrix2_nrows)

4


In [ ]:
def matrix_multiplication(matrix1, matrix 2):
  matrix1

In [5]:
nested_list = [[1, 2], [3, 4], [5]]
print(len(nested_list))
max = 0
for sublist in nested_list:
    if len(sublist) > max:
      max = len(sublist)
print(max)

3
2
